//! Help system — comprehensive CLI documentation.
//! Extracted from main.rs to keep the main file focused on logic.

pub fn print_help() {
    println!("wave-server v0.1.0 — OpenAI-compatible API for wave-engine models");
    println!();
    println!("USAGE:");
    println!("    wave-server <CHECKPOINT> [DATA] [OPTIONS]");
    println!();
    println!("ARGUMENTS:");
    println!("    CHECKPOINT      Path to a .bin checkpoint file trained by wave-engine.");
    println!("                    v2 checkpoints are self-describing (architecture stored");
    println!("                    in the header). v1 checkpoints need --n-bands etc.");
    println!();
    println!("    DATA            Path to the training data file (for vocabulary).");
    println!("                    Required for char/word modes — the server rebuilds the");
    println!("                    token mapping from this file. Not needed with --bpe.");
    println!();
    println!("SERVER:");
    println!("    --port N        Listen port                          [default: 8080]");
    println!("    --host ADDR     Bind address. Use 0.0.0.0 to listen  [default: 127.0.0.1]");
    println!("                    on all interfaces (LAN access).");
    println!("    --model-name S  Model name returned in API responses  [default: wave-engine]");
    println!("    --api-key KEY   Require Bearer token authentication. Clients must send");
    println!("                    'Authorization: Bearer <KEY>' header. The /health endpoint");
    println!("                    stays open without auth.              [default: none]");
    println!("    --memory FILE   Load/save wave memory state (.kwmf). Memory offsets inject");
    println!("                    into Kerr-ODE initial conditions. Accumulates experience");
    println!("                    across conversations. Auto-saves after each request.");
    println!("                    Creates fresh file if it doesn't exist. [default: none]");
    println!("    --gpu           Enable GPU acceleration for matmul operations.");
    println!("                    Requires compilation with --features gpu.");
    println!("                    Uses wgpu (Vulkan/Metal/DX12).          [default: off]");
    println!();
    println!("TOKENIZER:");
    println!("    --word          Word-level tokenization. Must match the mode used during");
    println!("                    training. Requires the DATA argument.");
    println!();
    println!("    --bpe FILE      BPE subword tokenization from a HuggingFace tokenizer.json.");
    println!("                    Must match the tokenizer used during training. The DATA");
    println!("                    argument is not needed — vocab comes from the tokenizer file.");
    println!();
    println!("    (default)       Character-level tokenization. Requires the DATA argument.");
    println!();
    println!("ARCHITECTURE (v1 checkpoints only — v2 self-describes):");
    println!("    These flags are only needed for v1 checkpoints that don't store their");
    println!("    architecture in the header. v2 checkpoints (saved by wave-engine v0.2+)");
    println!("    auto-detect all of these.");
    println!();
    println!("    --n-bands N     Harmonic frequency bands              [default: 384]");
    println!("    --n-head N      Attention heads                       [default: 12]");
    println!("    --n-layers N    Transformer blocks                    [default: 24]");
    println!("    --maestro-dim N Maestro bottleneck width               [default: 16]");
    println!("    --block-size N  Max sequence length                    [default: 256]");
    println!("    --rk4-steps N   ODE integration steps per layer        [default: 16]");
    println!();
    println!("ENDPOINTS:");
    println!("    POST /v1/chat/completions    Chat completions (JSON or SSE streaming)");
    println!("    GET  /v1/models              List available models");
    println!("    GET  /health                 Health check (no auth required)");
    println!();
    println!("TELEMETRY:");
    println!("    requests.jsonl  Written automatically for every chat completion request.");
    println!("                    Logs: timestamp, prompt/gen tokens, ms, tokens/sec,");
    println!("                    temperature, top_p, text preview. Survives crashes.");
    println!();
    println!("EXAMPLES:");
    println!("    # Serve a char-level model");
    println!("    wave-server checkpoint.bin data/input.txt");
    println!();
    println!("    # Serve with 512 BPE tokenizer");
    println!("    wave-server checkpoint.bin --bpe data/tokenizer_512.json");
    println!();
    println!("    # Custom port with API key authentication");
    println!("    wave-server checkpoint.bin data/input.txt --port 3000 --api-key mysecret");
    println!();
    println!("    # Listen on all interfaces (LAN access)");
    println!("    wave-server checkpoint.bin data/input.txt --host 0.0.0.0");
    println!();
    println!("    # Serve with wave memory");
    println!("    wave-server checkpoint.bin data/input.txt --memory memory.kwmf");
    println!();
    println!("    # v1 checkpoint with explicit architecture");
    println!("    wave-server old_checkpoint.bin data/input.txt --n-bands 84 --n-head 4 --n-layers 6");
    println!();
    println!("CONNECTING CHAT UIs:");
    println!("    Any client that speaks the OpenAI protocol can connect:");
    println!("    - LM Studio: Settings > Local Server > set endpoint to http://127.0.0.1:8080");
    println!("    - Open WebUI: Add connection with base URL http://127.0.0.1:8080");
    println!("    - curl:");
    println!("        curl http://127.0.0.1:8080/v1/chat/completions \\");
    println!("          -H 'Content-Type: application/json' \\");
    println!("          -d '{{\"model\":\"wave-engine\",\"messages\":[{{\"role\":\"user\",\"content\":\"Hello\"}}]}}'");
    println!();
    println!("    Verified with LM Studio 0.4.6. Streaming and non-streaming both supported.");
    println!();
    println!("SOURCE: https://github.com/atech-hub/wave-server");
    println!("ENGINE: https://github.com/atech-hub/wave-engine");
}
